
structdir = '/mnt/data/Try_full_run/Working_Memory/AllDataStructs/StableIntersectCols';
outputdir = '/mnt/data/Try_full_run/Working_Memory/ROItSeries';
pdirs = {
    '/mnt/data/Try_full_run/Working_Memory/S22/Session1/mrVistaSession',... %1
    '/mnt/data/Try_full_run/Working_Memory/S16/Session1/mrVistaSession',... %2
    '/mnt/data/Try_full_run/Working_Memory/S14/FRESH_WorkingMemory_S14/mrVistaSession',...%3
    '/mnt/data/Try_full_run/Working_Memory/S01/FRESH_WorkingMemory_S01_All/mrVistaSession',...%4
    '/mnt/data/Try_full_run/Working_Memory/S19/FRESH_WorkingMemory_S19/mrVistaSession',...%5
    '/mnt/data/Try_full_run/Working_Memory/S13/FRESH_WorkingMemory_S13_All/mrVistaSession' %6
};

ppNames = {
    'DataS22',...
    'DataS16',...
    'DataS14',...
    'DataS01',...
    'DataS19',...
    'DataS13',...
    };

dtdirs = {
    'Progressive',...
    'OddScans',...
    'EvenScans',...
    'ConstantDifficulty',...
    'ConstantOrientation',...
    'RandomOrder',...
    };
dtnames = {
    'Progressive',...
    'Odd',...
    'Even',...
    'Difficulty',...
    'Orientation',...
    'RandomOrder',...
    };
ROIs = {
    'VMF1',...
    'VMF2',...
    'VMF3',...
    'VMIPS0',...
    'VMIPS1',...
    'VMIPS2',...
    'VMIPS3',...
    'VMIPS4',...
    'VMIPS5',...
    'VMT1',...
    'VMT2',...
    };
hemis = {
    'Left',...
    'Right',...
    };
%Lin2dOvalGaussian
modelName = 'Log2Lin';
%DataTypes: Odd, Even, All
for n = 1:6
cd(structdir);
subName = ppNames{n};
load([subName, '.mat'])
for ndt = 1:5
    tSeriesdir = [pdirs{n}, '/Gray/', dtdirs{ndt}, 'Averages (L1)/TSeries/Scan1'];
    cd(tSeriesdir)
    load('tSeries1.mat')
    tSeriesComplete=tSeries;
    cd(outputdir)
    for numRoi = 1:11
        for hemi = 1:2
            roiInds = eval([subName, '.', ROIs{numRoi}, '.', hemis{hemi}, '.', modelName, '.', dtnames{ndt}, '.roiIndices']);    
            newname = ['P',num2str(n),hemis{hemi},ROIs{numRoi},'VSTM',dtnames{ndt}];
            tSeries = tSeriesComplete(:,roiInds);
            save([newname,'.mat'],'tSeries')
        end
    end
end
end

outputdir = '/mnt/data/Try_full_run/Working_Memory/ROItSeries/RandomOrder';
% RandomOrder
for n = [1,3,4,5,6]
cd(structdir);
subName = ppNames{n};
load([subName, '.mat'])
for ndt = 1:6 % Not dt but WhichAverage
    tSeriesdir = [pdirs{n}, '/Gray/', dtdirs{6}, 'Averages (L1)/TSeries/Scan', num2str(ndt)];
    cd(tSeriesdir)
    load('tSeries1.mat')
    tSeriesComplete=tSeries;
    cd(outputdir)
    for numRoi = 1:11
        for hemi = 1:2
            roiInds = eval([subName, '.', ROIs{numRoi}, '.', hemis{hemi}, '.', modelName, '.', dtnames{6}, '.roiIndices']);    
            newname = ['P',num2str(n),hemis{hemi},ROIs{numRoi},'VSTM',dtnames{6}, num2str(ndt)];
            tSeries = tSeriesComplete(:,roiInds);
            save([newname,'.mat'],'tSeries')
        end
    end
end
end


